### ISSUE TITLE
DNS recovery feature branch

### ISSUE THREAD

**Issue by Raynos** [uber/node-statsd-client#8]
There is a feature branch open `0.0.4-dns-recovery` to handle the various DNS recovery issues
## Main issues
- [x] #4 Adding tests for UDP sockets
- [x] #3 work around lib/dgram.js node core memory leak
- [x] #5 remove stream helper dead code
- [x] #6 remove timeout dead code.
- [x] #7 implement static DNS resolvement.
- [x] #11 Implement a static ip seed list.
- [x] #10 coalesce multiple packets together
- [x] #12 implement a TTL refresh of the DNS lookup
- [x] #9 implement proper error handling on the UDP socket 
- [x] #14 Revert the cleanup timeout code.
- [x] #15 Support statsite with trailing new line.
- [x] #16 Get gauge() to write to the socket directly
## Future improvements
- [ ] Rate limit the throughput in a statsd client.
- [ ] implement round robin hashing to multiple IPs
- [ ] warn about exceeding the `sendQueue`.
- [ ] allow passing in a logger.

cc @sh1mmer @kriskowal
